name    'envato-hubot'
version '0.0.1'
source 'git@github.com:envato/puppet-hubot.git'
author 'envato'
license 'Apache License, Version 2.0'
summary 'Installs and configures Hubot'
description 'Installs and configures Hubot'
project_page 'https://github.com/envato/puppet-hubot'
